services:
    translator_tool.data_collector:
        class: AECF\TranslatorToolBundle\Collector\TranslatorToolDataCollector
        arguments:
            - "@translator"
            - "@translator_tool"
            - "%translator_tool.auto_create_missing.enabled%"
            - "%%kernel.root_dir%"
        public: false
        tags:
            - { name: data_collector, template: "TranslatorToolBundle:DataCollector:translator_tool.html.twig", id: "translator_tool" }

    translator_tool:
        class: AECF\TranslatorToolBundle\Service\TranslatorToolService
        arguments:
            - "@catalogue_loader"
            - "@catalogue_editor"
            - "%translator_tool.enabled_locales%"
            - "%translator_tool.auto_create_missing.enabled%"
            - "%translator_tool.auto_create_missing.formats%"
            - "%kernel.root_dir%"
            - "@kernel"

    catalogue_loader:
        class: AECF\TranslatorToolBundle\Loader\MessageCatalogueLoader
        arguments: ['@translation.loader']

    catalogue_editor:
        class: AECF\TranslatorToolBundle\Editor\CatalogueEditor
        public: false
        arguments:
            - "@translation.writer"

    translation.twig_extension:
        class: AECF\TranslatorToolBundle\Twig\TranslatorToolExtension
        arguments: ['@translator']
        public: false
        tags:
            - { name: twig.extension }

    translator.listener:
        class: AECF\TranslatorToolBundle\Listener\TranslatorToolProfilerListener
        arguments: ['@twig']
        tags:
            - { name: kernel.event_subscriber }
