parameters:
    translator_tool.auto_create_missing.enabled:
    translator_tool.auto_create_missing.format:

services:
    translator_tool.data_collector:
        class: AECF\TranslatorToolBundle\DataCollector\TranslatorToolDataCollector
        arguments:
            - @translator.data_collector
            - @translator_tool
            - %translator_tool.auto_create_missing.enabled%
        tags:
            - {
                name: data_collector,
                template: "TranslatorToolBundle:DataCollector:translator_tool.html.twig",
                id: "translator_tool"
              }

    translator_tool:
        class: AECF\TranslatorToolBundle\Service\TranslatorToolService
        arguments: ['@catalogue_loader', '@translation.writer', '%locale%', '%translator_tool.auto_create_missing.format%', '%kernel.root_dir%']

    catalogue_loader:
        class: AECF\TranslatorToolBundle\Loader\MessageCatalogueLoader
        arguments: ['@translation.loader']
