parameters:
    translator_tool.auto_create_missing.enabled:
    translator_tool.auto_create_missing.format:

services:
    translator_tool:
        class: AECF\TranslatorToolBundle\Service\TranslatorToolService
        arguments:
            - '@catalogue_loader'
            - '@catalogue_editor'
            - "%translator_tool.enabled_locales%"
            - "%translator_tool.formats%"
            - '%kernel.root_dir%'

    translator_tool.data_collector:
        class: AECF\TranslatorToolBundle\Collector\TranslatorToolDataCollector
        arguments:
            - "@translator"
            - "@translator_tool"
            - "%translator_tool.auto_create_missing.enabled%"
            - "%%kernel.root_dir%"
        public: false
        tags:
            - { name: data_collector, template: "TranslatorToolBundle:DataCollector:translator_tool.html.twig", id: "translator_tool" }

    catalogue_loader:
        class: AECF\TranslatorToolBundle\Loader\MessageCatalogueLoader
        arguments: ['@translation.loader']
        public: false

    catalogue_editor:
        class: AECF\TranslatorToolBundle\Editor\CatalogueEditor
        public: false
        arguments:
            - "@translation.writer"
