language: php
sudo: false
php:
    - hhvm
    - 5.6
    - 7.0

matrix:
    include:
        - php: 5.6
          env: SYMFONY_VERSION='2.8.*@dev'
        - php: 7.0
          env: SYMFONY_VERSION='2.8.*@dev'
        - php: 5.6
          env: SYMFONY_VERSION='3.0.*@dev'
        - php: 7.0
          env: SYMFONY_VERSION='3.0.*@dev'

before_install:
    - composer self-update
    - if [ "$DEPENDENCIES" == "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
    - if [ "$SYMFONY_VERSION" != "" ]; then composer --no-update require symfony/symfony:${SYMFONY_VERSION}; fi;

install: composer update $COMPOSER_FLAGS

script: vendor/bin/phpunit